global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'manager'
    metrics_path: /metrics
    static_configs:
      - targets: ['manager:8000']

  - job_name: 'worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['worker:8001']

  - job_name: 'evaluator'
    metrics_path: /metrics
    static_configs:
      - targets: ['evaluator:8002']

  - job_name: 'db-log-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['db-log-exporter:9610']
