apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: false

  - name: PostgreSQL
    uid: postgresql
    type: postgres
    access: proxy
    url: postgres:5432
    database: agent_system
    user: agent
    secureJsonData:
      password: agent1234
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
    editable: false
